### ISSUE TITLE
Curseforge has an issue with your choice of licensing

### ISSUE THREAD

**Issue by TwoPointInfinity** [rutrum/replant-swamp-trees#9]
I am unable to use your mod in a public modpack for curseforge. 

If this is intended, perfect. Close the ticket. 
https://gyazo.com/12cf53c74ad9efa98c8143451f1887eb

**Comment by rutrum** [comment]
Interesting.  I would like my license to be very open, and allow use in modpacks, without explicit permission.  It's currently using the license provided by the fabric mod example project, which is CC0.  I think this is an odd choice, since a mod or more of a software product than a work of art?  Not sure, I'm not super versed on my licenses.

Do you have a suggestion on the license?  My first instinct is GPLv3, but I'm not entirely certain what constraints need to be met for the curseforge mods.

**Comment by rutrum** [comment]
Ah, so I never explicitly declared this in curseforge, so it defaulted to ARR.  I've changed the curseforge page to be GLPv3.  Let me know if that works now.  Thanks for using my mod in a modpack :)

**Comment by rutrum** [comment]
I think I've resolved the licensing issue on curseforge, so I'll close this ticket.  Feel free to reopen if the problem still persists.
